/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Outfit', 'Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
        'headline-xl': ['Outfit', 'sans-serif'],
        'headline-lg': ['Outfit', 'sans-serif'],
        'headline-md': ['Outfit', 'sans-serif'],
        'headline-sm': ['Outfit', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Outfit', 'sans-serif'],
      },
      colors: {
        brand: {
          DEFAULT: 'var(--color-brand)',
          hover: 'var(--color-brand-hover)',
          light: 'var(--color-brand-light)',
          subtle: 'var(--color-brand-subtle)',
        },
        neutral: {
          bg1: 'var(--color-bg-1)',
          bg2: 'var(--color-bg-2)',
          bg3: 'var(--color-bg-3)',
          bg4: 'var(--color-bg-4)',
          bg5: 'var(--color-bg-5)',
          bg6: 'var(--color-bg-6)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
        },
        border: {
          subtle: 'var(--color-border-subtle)',
          DEFAULT: 'var(--color-border-default)',
          strong: 'var(--color-border-strong)',
        },
        status: {
          success: 'var(--color-success)',
          warning: 'var(--color-warning)',
          error: 'var(--color-error)',
          info: 'var(--color-info)',
        },
        // Stitch design system colors
        primary: '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'secondary': '#5d5e60',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0dfe1',
        'on-secondary-container': '#626264',
        'tertiary': '#7e3000',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a44100',
        'on-tertiary-container': '#ffd2be',
        'background': '#fcf8ff',
        'on-background': '#1b1b24',
        'surface': '#fcf8ff',
        'on-surface': '#1b1b24',
        'surface-variant': '#e4e1ee',
        'on-surface-variant': '#464555',
        'outline': '#777587',
        'outline-variant': '#c7c4d8',
        'inverse-surface': '#302f39',
        'inverse-on-surface': '#f3effc',
        'inverse-primary': '#c3c0ff',
        'primary-fixed': '#e2dfff',
        'on-primary-fixed': '#0f0069',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed-variant': '#3323cc',
        'secondary-fixed': '#e3e2e4',
        'secondary-fixed-dim': '#c6c6c8',
        'on-secondary-fixed': '#1a1c1d',
        'on-secondary-fixed-variant': '#464749',
        'tertiary-fixed': '#ffdbcc',
        'tertiary-fixed-dim': '#ffb695',
        'on-tertiary-fixed': '#351000',
        'on-tertiary-fixed-variant': '#7b2f00',
        'surface-dim': '#dcd8e5',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#f0ecf9',
        'surface-container-high': '#eae6f4',
        'surface-container-highest': '#e4e1ee',
        'hazy-lavender': 'rgba(165, 180, 252, 0.18)',
        'hazy-rose': 'rgba(244, 143, 177, 0.14)',
        'hazy-mint': 'rgba(167, 243, 208, 0.11)',
        'surface-bg': 'rgba(255, 255, 255, 0.35)',
        'text-primary': '#1E293B',
        'text-secondary': '#475569',
        'text-muted': '#64748B',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.25rem',
        full: '9999px',
      },
      boxShadow: {
        glow: '0 0 20px rgba(99, 102, 241, 0.15)',
        'glow-success': '0 0 20px rgba(16, 185, 129, 0.15)',
        'glow-lg': '0 0 40px rgba(99, 102, 241, 0.20)',
        'glass-shadow': '0 8px 32px 0 rgba(31, 38, 135, 0.03)',
        'btn-shadow': '0 4px 16px -2px rgba(99, 102, 241, 0.08)',
      },
      backdropBlur: {
        xs: '2px',
      },
      animation: {
        'fade-in': 'fadeIn 0.25s ease-out',
        'slide-up': 'slideUp 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'slide-down': 'slideDown 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      spacing: {
        'safe-top': 'env(safe-area-inset-top)',
        'safe-bottom': 'env(safe-area-inset-bottom)',
        'safe-left': 'env(safe-area-inset-left)',
        'safe-right': 'env(safe-area-inset-right)',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '2rem',
        'margin-desktop': '2.5rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'container-max': '1280px',
      },
      minHeight: {
        'touch': '44px',
      },
      minWidth: {
        'touch': '44px',
      },
    },
  },
  plugins: [],
};
